### ISSUE TITLE
LSTAR插件乱码问题！！！

### ISSUE THREAD

**Issue by deepblueye** [lintstar/LSTAR#12]
载入LSTAR插件，当前cs版本是4.9.1版本，发现菜单显示全部是乱码，希望作者帮忙修复一下乱码问题。
<img width="244" alt="image" src="https://github.com/lintstar/LSTAR/assets/15513999/85bd2e68-9b08-4f87-933a-1d7a106604bb">

**Comment by lintstar** [comment]
可以看下 #7
