### ISSUE TITLE
LSTAR-master\scripts\AuthMaintainSchTask.exe is not a process assembly (.NET EXE)

### ISSUE THREAD

**Issue by wgetnz** [lintstar/LSTAR#3]
RT

**Comment by lintstar** [comment]
感谢师傅 ~ 是文件路径问题： https://github.com/lintstar/LSTAR/commit/a75fe22208506816cc99c8189ec040694afbd095

**Comment by junanc** [comment]
这个要怎么修复啊，我下载最新的也还是存在这个问题

**Comment by lintstar** [comment]
> 这个要怎么修复啊，我下载最新的也还是存在这个问题

git clone 仓库代码，release 中的压缩包没有修复
