### ISSUE TITLE
Garbled code?

### ISSUE THREAD

**Issue by vgi777** [lintstar/LSTAR#4]
<img width="281" alt="image" src="https://user-images.githubusercontent.com/98085865/152731845-7e21e1bf-a035-42e7-bd58-60a3ce19dc52.png">

**Comment by lintstar** [comment]
Please add the following parameters to the startup script of the Cobaltstrike client
```
-Dfile.encoding=UTF-8
```
like this
```
java -Dfile.encoding=UTF-8 -jar cobaltstrike.jar
```
